name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK (cmdline-tools latest)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            platforms;android-34
            build-tools;34.0.0
            ndk;26.1.10909125
            cmake;3.22.1

      - name: Verify SDK tools
        run: |
          echo "sdkmanager version:"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --version

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew clean assembleRelease --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobileblox-apk
          path: app/build/outputs/**/*.apk
